package com.UserService.Seed;

import com.UserService.Model.Bank;
import com.UserService.Repository.BankRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import java.util.Arrays;
import java.util.List;

@Component
@RequiredArgsConstructor
public class BankDataSeeder implements CommandLineRunner {

    private final BankRepository bankRepository;


    @Override
    public void run(String... args) throws Exception {
        if (bankRepository.count() == 0) {
            List<Bank> banks = Arrays.asList(
                    new Bank("9mobile 9Payment Service Bank", "9mobile-9payment-service-bank-ng", "120001", "120001", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Abbey Mortgage Bank", "abbey-mortgage-bank-ng", "404", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Above Only MFB", "above-only-mfb", "51204", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Abulesoro MFB", "abulesoro-mfb-ng", "51312", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Access Bank", "access-bank", "044", "044150149", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Access Bank (Diamond)", "access-bank-diamond", "063", "063150162", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Accion Microfinance Bank", "accion-microfinance-bank-ng", "602", "", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Ahmadu Bello University Microfinance Bank", "ahmadu-bello-university-microfinance-bank-ng", "50036", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Airtel Smartcash PSB", "airtel-smartcash-psb-ng", "120004", "120004", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("AKU Microfinance Bank", "aku-mfb", "51336", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Akuchukwu Microfinance Bank Limited", "akuchukwu-microfinance-bank-limited-ng", "090561", "090561", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("ALAT by WEMA", "alat-by-wema", "035A", "035150103", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Amegy Microfinance Bank", "amegy-microfinance-bank-ng", "090629", "090629", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Amju Unique MFB", "amju-unique-mfb", "50926", "511080896", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("AMPERSAND MICROFINANCE BANK", "ampersand-microfinance-bank-ng", "51341", "", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Aramoko MFB", "aramoko-mfb", "50083", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("ASO Savings and Loans", "asosavings", "401", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Astrapolaris MFB LTD", "astrapolaris-mfb", "MFB50094", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("AVUENEGBE MICROFINANCE BANK", "avuenegbe-microfinance-bank-ng", "090478", "090478", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Bainescredit MFB", "bainescredit-mfb", "51229", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Banc Corp Microfinance Bank", "banc-corp-microfinance-bank-ng", "50117", "50117", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Beststar Microfinance Bank", "beststar-microfinance-bank-ng", "50123", "090615", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Bowen Microfinance Bank", "bowen-microfinance-bank", "50931", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Branch International Financial Services Limited", "branch", "FC40163", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Carbon", "carbon", "565", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("CASHCONNECT MFB", "cashconnect-mfb-ng", "865", "865", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("CEMCS Microfinance Bank", "cemcs-microfinance-bank", "50823", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Chanelle Microfinance Bank Limited", "chanelle-microfinance-bank-limited-ng", "50171", "50171", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Chikum Microfinance bank", "chikum-microfinance-bank-ng", "312", "null", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Citibank Nigeria", "citibank-nigeria", "023", "023150005", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("CITYCODE MORTAGE BANK", "citycode-mortage-bank-ng", "070027", "070027", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Consumer Microfinance Bank", "consumer-microfinance-bank-ng", "50910", "50910", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Corestep MFB", "corestep-mfb", "50204", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Coronation Merchant Bank", "coronation-merchant-bank-ng", "559", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("County Finance Limited", "county-finance-limited", "FC40128", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Crescent MFB", "crescent-mfb", "51297", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Crust Microfinance Bank", "crust-microfinance-bank-ng", "090560", "", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Davenport MICROFINANCE BANK", "davenport-microfinance-bank-ng", "51334", "51334", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Dot Microfinance Bank", "dot-microfinance-bank-ng", "50162", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Ecobank Nigeria", "ecobank-nigeria", "050", "050150010", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Ekimogun MFB", "ekimogun-mfb-ng", "50263", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Ekondo Microfinance Bank", "ekondo-microfinance-bank-ng", "098", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("EXCEL FINANCE BANK", "excel-finance-bank-ng", "090678", "090678", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Eyowo", "eyowo", "50126", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Fairmoney Microfinance Bank", "fairmoney-microfinance-bank-ng", "51318", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Fedeth MFB", "fedeth-mfb-ng", "50298", "090482", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Fidelity Bank", "fidelity-bank", "070", "070150003", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Firmus MFB", "firmus-mfb", "51314", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("First Bank of Nigeria", "first-bank-of-nigeria", "011", "011151003", "ibank", false, true, true, "Nigeria", "NGN", false),
                    new Bank("First City Monument Bank", "first-city-monument-bank", "214", "214150018", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("FIRST ROYAL MICROFINANCE BANK", "first-royal-microfinance-bank-ng", "090164", "090164", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("FirstTrust Mortgage Bank Nigeria", "firsttrust-mortgage-bank-nigeria-ng", "413", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("FLOURISH MFB", "flourish-mfb-ng", "50315", "50315", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("FSDH Merchant Bank Limited", "fsdh-merchant-bank-limited", "501", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("FUTMINNA MICROFINANCE BANK", "futminna-microfinance-bank-ng", "832", "832", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Gateway Mortgage Bank LTD", "gateway-mortgage-bank", "812", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Globus Bank", "globus-bank", "00103", "103015001", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Goldman MFB", "goldman-mfb-ng", "090574", "950356", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("GoMoney", "gomoney", "100022", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("GOOD SHEPHERD MICROFINANCE BANK", "good-shepherd-microfinance-bank-ng", "090664", "090664", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Goodnews Microfinance Bank", "goodnews-microfinance-bank-ng", "50739", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Greenwich Merchant Bank", "greenwich-merchant-bank-ng", "562", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Guaranty Trust Bank", "guaranty-trust-bank", "058", "058152036", "ibank", true, true, true, "Nigeria", "NGN", false),
                    new Bank("Hackman Microfinance Bank", "hackman-microfinance-bank", "51251", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Hasal Microfinance Bank", "hasal-microfinance-bank", "50383", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Heritage Bank", "heritage-bank", "030", "030159992", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("HopePSB", "hopepsb-ng", "120002", "120002", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Ibile Microfinance Bank", "ibile-mfb", "51244", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Ikoyi Osun MFB", "ikoyi-osun-mfb", "50439", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Ilaro Poly Microfinance Bank", "ilaro-poly-microfinance-bank-ng", "50442", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Imowo MFB", "imowo-mfb-ng", "50453", "50453", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("IMPERIAL HOMES MORTAGE BANK", "imperial-homes-mortage-bank-ng", "415", "100024", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Infinity MFB", "infinity-mfb", "50457", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Jaiz Bank", "jaiz-bank", "301", "301080020", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Kadpoly MFB", "kadpoly-mfb", "50502", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("KANOPOLY MFB", "kanopoly-mfb-ng", "51308", "090592", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Keystone Bank", "keystone-bank", "082", "082150017", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Kredi Money MFB LTD", "kredi-money-mfb", "50200", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Kuda Bank", "kuda-bank", "50211", "", "digitalbankmandate", true, true, true, "Nigeria", "NGN", false),
                    new Bank("Lagos Building Investment Company Plc.", "lbic-plc", "90052", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Links MFB", "links-mfb", "50549", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Living Trust Mortgage Bank", "living-trust-mortgage-bank", "031", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("LOMA MFB", "loma-mfb-ng", "50491", "090620", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Lotus Bank", "lotus-bank", "303", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("MAINSTREET MICROFINANCE BANK", "mainstreet-microfinance-bank-ng", "090171", "090171", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Mayfair MFB", "mayfair-mfb", "50563", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Mint MFB", "mint-mfb", "50304", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Money Master PSB", "money-master-psb-ng", "946", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Moniepoint MFB", "moniepoint-mfb-ng", "50515", "null", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("MTN Momo PSB", "mtn-momo-psb-ng", "120003", "120003", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("MUTUAL BENEFITS MICROFINANCE BANK", "mutual-benefits-microfinance-bank-ng", "090190", "090190", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("NDCC MICROFINANCE BANK", "ndcc-microfinance-bank-ng", "090679", "090679", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Nigerian Navy Microfinance Bank Limited", "nigerian-navy-microfinance-bank-limited-ng", "51142", "090263", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("NPF MICROFINANCE BANK", "npf-microfinance-bank-ng", "50629", "50629", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("OPay Digital Services Limited (OPay)", "paycom", "999992", "", "ibank", true, true, true, "Nigeria", "NGN", false),
                    new Bank("Optimus Bank Limited", "optimus-bank-ltd", "107", "00107", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Paga", "paga", "100002", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("PalmPay", "palmpay", "999991", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Parallex Bank", "parallex-bank", "104", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Parkway - ReadyCash", "parkway-ready-cash", "311", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("PATHFINDER MICROFINANCE BANK LIMITED", "pathfinder-microfinance-bank-limited-ng", "090680", "090680", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Paystack-Titan", "titan-paystack", "100039", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Peace Microfinance Bank", "peace-microfinance-bank-ng", "50743", "50743", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("PECANTRUST MICROFINANCE BANK LIMITED", "pecantrust-microfinance-bank-limited-ng", "51226", "51226", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Personal Trust MFB", "personal-trust-mfb-ng", "51146", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Petra Mircofinance Bank Plc", "petra-microfinance-bank-plc", "50746", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("PFI FINANCE COMPANY LIMITED", "pfi-finance-company-limited-ng", "050021", "050021", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Platinum Mortgage Bank", "platinum-mortgage-bank-ng", "268", "null", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Pocket App", "pocket", "00716", "00716", "digitalbankmandate", true, true, true, "Nigeria", "NGN", false),
                    new Bank("Polaris Bank", "polaris-bank", "076", "076151006", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Polyunwana MFB", "polyunwana-mfb-ng", "50864", "null", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("PremiumTrust Bank", "premiumtrust-bank-ng", "105", "000031", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("PROSPERIS FINANCE LIMITED", "prosperis-finance-limited-ng", "050023", "050023", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Providus Bank", "providus-bank", "101", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("QuickFund MFB", "quickfund-mfb", "51293", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Rand Merchant Bank", "rand-merchant-bank", "502", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("RANDALPHA MICROFINANCE BANK", "randalpha-microfinance-bank-ng", "090496", "090496", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Refuge Mortgage Bank", "refuge-mortgage-bank", "90067", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("REHOBOTH MICROFINANCE BANK", "rehoboth-microfinance-bank-ng", "50761", "090463", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Rephidim Microfinance Bank", "rephidim", "50994", "221151615", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Rigo Microfinance Bank Limited", "rigo-microfinance-bank-limited-ng", "51286", "51286", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("ROCKSHIELD MICROFINANCE BANK", "rockshield-microfinance-bank-ng", "50767", "", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Rubies MFB", "rubies-mfb", "125", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Safe Haven MFB", "safe-haven-mfb-ng", "51113", "51113", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Safe Haven Microfinance Bank Limited", "safe-haven-microfinance-bank-limited-ng", "951113", "", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("SAGE GREY FINANCE LIMITED", "sage-grey-finance-limited-ng", "40165", "null", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Shield MFB", "shield-mfb-ng", "50582", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Signature Bank Ltd", "signature-bank-ltd-ng", "106", "000034", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Solid Allianze MFB", "solid-allianze-mfb", "51062", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Solid Rock MFB", "solid-rock-mfb", "50800", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Sparkle Microfinance Bank", "sparkle-microfinance-bank", "51310", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Stanbic IBTC Bank", "stanbic-ibtc-bank", "221", "221159522", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Standard Chartered Bank", "standard-chartered-bank", "068", "068150015", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("STANFORD MICROFINANCE BANK", "stanford-microfinance-bank-ng", "090162", "090162", "", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Stellas MFB", "stellas-mfb", "51253", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Sterling Bank", "sterling-bank", "232", "232150016", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Suntrust Bank", "suntrust-bank", "100", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Supreme MFB", "supreme-mfb-ng", "50968", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("TAJ Bank", "taj-bank", "302", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Tangerine Money", "tangerine-money", "51269", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("TCF MFB", "tcf-mfb", "51211", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Titan Bank", "titan-bank", "102", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("U&C Microfinance Bank Ltd (U AND C MFB)", "uc-microfinance-bank-ltd-u-and-c-mfb-ng", "50840", "50840", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Uhuru MFB", "uhuru-mfb-ng", "51322", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Unaab Microfinance Bank Limited", "unaab-microfinance-bank-limited-ng", "50870", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Unical MFB", "unical-mfb", "50871", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Unilag Microfinance Bank", "unilag-microfinance-bank-ng", "51316", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Union Bank of Nigeria", "union-bank-of-nigeria", "032", "032080474", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("United Bank For Africa", "united-bank-for-africa", "033", "033153513", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Unity Bank", "unity-bank", "215", "215154097", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("Uzondu Microfinance Bank Awka Anambra State", "uzondu-microfinance-bank-awka-anambra-state-ng", "50894", "50894", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Vale Finance Limited", "vale-finance", "050020", "", "emandate", false, true, true, "Nigeria", "NGN", false),
                    new Bank("VFD Microfinance Bank Limited", "vfd", "566", "", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Waya Microfinance Bank", "waya-microfinance-bank-ng", "51355", "51355", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Wema Bank", "wema-bank", "035", "035150103", null, false, true, true, "Nigeria", "NGN", false),
                    new Bank("Zenith Bank", "zenith-bank", "057", "057150013", "emandate", false, true, true, "Nigeria", "NGN", false)
            );

            bankRepository.saveAll(banks);
        }
    }
}